### ISSUE TITLE
D3QN

### ISSUE THREAD

**Issue by hurong971013** [Godcreatebugs/ENPM808-Monocular-Obstacle-Avoidance-Using-D3QN-Network#1]
There is a paper on Towards Monocular Vision based Obstacle
Avoidance through Deep Reinforcement Learning, could you please tell me does this project come from this paper

**Comment by Godcreatebugs** [comment]
Thanks for your email. Yes it is the same paper but the code I have kept
proprietary(My implementation) because of my university restriction as I
have taken this as a independent study and this code will be deleted after
sometimes on github as I am experimenting with these codes.

**Comment by hurong971013** [comment]
Sorry, do you have a complete image data set of this code? The original author's data set link is invalid. Can you help me?
